INSERT IGNORE INTO artists(artist_name) VALUES ("G-Eazy & Halsey");
INSERT IGNORE INTO artists(artist_name) VALUES ("NF");
INSERT IGNORE INTO artists(artist_name) VALUES ("Bruno Mars & Cardi B");
INSERT IGNORE INTO artists(artist_name) VALUES ("Ed Sheeran");
INSERT IGNORE INTO artists(artist_name) VALUES ("Zedd, Maren Morris & Grey");
INSERT IGNORE INTO artists(artist_name) VALUES ("Bebe Rexha & Florida Georgia Line");
INSERT IGNORE INTO artists(artist_name) VALUES ("Dua Lipa");
INSERT IGNORE INTO artists(artist_name) VALUES ("MAX Featuring gnash");
INSERT IGNORE INTO artists(artist_name) VALUES ("Camila Cabello");
INSERT IGNORE INTO artists(artist_name) VALUES ("Selena Gomez X Marshmello");
INSERT IGNORE INTO artists(artist_name) VALUES ("The Weeknd & Kendrick Lamar");
INSERT IGNORE INTO artists(artist_name) VALUES ("Drake");
INSERT IGNORE INTO artists(artist_name) VALUES ("Camila Cabello Featuring Young Thug");
INSERT IGNORE INTO artists(artist_name) VALUES ("Halsey");
INSERT IGNORE INTO artists(artist_name) VALUES ("Imagine Dragons");
INSERT IGNORE INTO artists(artist_name) VALUES ("Maroon 5");
INSERT IGNORE INTO artists(artist_name) VALUES ("Justin Timberlake Featuring Chris Stapleton");
INSERT IGNORE INTO artists(artist_name) VALUES ("Lauv");
INSERT IGNORE INTO artists(artist_name) VALUES ("Marshmello & Anne-Marie");
INSERT IGNORE INTO artists(artist_name) VALUES ("Demi Lovato");
INSERT IGNORE INTO artists(artist_name) VALUES ("Meghan Trainor");
INSERT IGNORE INTO artists(artist_name) VALUES ("N*E*R*D & Rihanna");
INSERT IGNORE INTO artists(artist_name) VALUES ("Kendrick Lamar & SZA");
INSERT IGNORE INTO artists(artist_name) VALUES ("Bazzi");
INSERT IGNORE INTO artists(artist_name) VALUES ("5 Seconds Of Summer");
INSERT IGNORE INTO artists(artist_name) VALUES ("Dua Lipa");
INSERT IGNORE INTO artists(artist_name) VALUES ("Troye Sivan");
INSERT IGNORE INTO artists(artist_name) VALUES ("Niall Horan");
INSERT IGNORE INTO artists(artist_name) VALUES ("Post Malone Featuring Ty Dolla $ign");
INSERT IGNORE INTO artists(artist_name) VALUES ("Jack & Jack");
INSERT IGNORE INTO artists(artist_name) VALUES ("P!nk");
INSERT IGNORE INTO artists(artist_name) VALUES ("Taylor Swift");
INSERT IGNORE INTO artists(artist_name) VALUES ("Thirty Seconds To Mars");
INSERT IGNORE INTO artists(artist_name) VALUES ("Why Don't We");
INSERT IGNORE INTO artists(artist_name) VALUES ("Alice Merton");
INSERT IGNORE INTO artists(artist_name) VALUES ("Foster The People");
INSERT IGNORE INTO artists(artist_name) VALUES ("Kendrick Lamar Featuring Zacari");
INSERT IGNORE INTO artists(artist_name) VALUES ("Kent Jones");
INSERT IGNORE INTO artists(artist_name) VALUES ("Logic & Marshmello");
INSERT IGNORE INTO artists(artist_name) VALUES ("Hayley Kiyoko");
INSERT IGNORE INTO artists(artist_name) VALUES ("Imagine Dragons");
INSERT IGNORE INTO artists(artist_name) VALUES ("Imagine Dragons");
INSERT IGNORE INTO artists(artist_name) VALUES ("Portugal. The Man");
INSERT IGNORE INTO artists(artist_name) VALUES ("Imagine Dragons");
INSERT IGNORE INTO artists(artist_name) VALUES ("Bad Wolves");
INSERT IGNORE INTO artists(artist_name) VALUES ("Foster The People");
INSERT IGNORE INTO artists(artist_name) VALUES ("Alice Merton");
INSERT IGNORE INTO artists(artist_name) VALUES ("WALK THE MOON");
INSERT IGNORE INTO artists(artist_name) VALUES ("Shinedown");
INSERT IGNORE INTO artists(artist_name) VALUES ("Imagine Dragons");
INSERT IGNORE INTO artists(artist_name) VALUES ("Five Finger Death Punch");
INSERT IGNORE INTO artists(artist_name) VALUES ("Portugal. The Man");
INSERT IGNORE INTO artists(artist_name) VALUES ("lovelytheband");
INSERT IGNORE INTO artists(artist_name) VALUES ("Three Days Grace");
INSERT IGNORE INTO artists(artist_name) VALUES ("James Bay");
INSERT IGNORE INTO artists(artist_name) VALUES ("The Band Of Heathens");
INSERT IGNORE INTO artists(artist_name) VALUES ("James Bay");
INSERT IGNORE INTO artists(artist_name) VALUES ("Muse");
INSERT IGNORE INTO artists(artist_name) VALUES ("Nathaniel Rateliff & The Night Sweats");
INSERT IGNORE INTO artists(artist_name) VALUES ("Breaking Benjamin");
INSERT IGNORE INTO artists(artist_name) VALUES ("The Killers");
INSERT IGNORE INTO artists(artist_name) VALUES ("Godsmack");
INSERT IGNORE INTO artists(artist_name) VALUES ("Two Feet");
INSERT IGNORE INTO artists(artist_name) VALUES ("Vance Joy");
INSERT IGNORE INTO artists(artist_name) VALUES ("Greta Van Fleet");
INSERT IGNORE INTO artists(artist_name) VALUES ("Sufjan Stevens");
INSERT IGNORE INTO artists(artist_name) VALUES ("Pop Evil");
INSERT IGNORE INTO artists(artist_name) VALUES ("Fall Out Boy");
INSERT IGNORE INTO artists(artist_name) VALUES ("Papa Roach");
INSERT IGNORE INTO artists(artist_name) VALUES ("The Neighbourhood");
INSERT IGNORE INTO artists(artist_name) VALUES ("Thirty Seconds To Mars");
INSERT IGNORE INTO artists(artist_name) VALUES ("Pearl Jam");
INSERT IGNORE INTO artists(artist_name) VALUES ("Manchester Orchestra");
INSERT IGNORE INTO artists(artist_name) VALUES ("Imagine Dragons + Khalid");
INSERT IGNORE INTO artists(artist_name) VALUES ("Sir Sly");
INSERT IGNORE INTO artists(artist_name) VALUES ("SYML");
INSERT IGNORE INTO artists(artist_name) VALUES ("CHVRCHES");
INSERT IGNORE INTO artists(artist_name) VALUES ("The Neighbourhood");
INSERT IGNORE INTO artists(artist_name) VALUES ("Noah Kahan & Julia Michaels");
INSERT IGNORE INTO artists(artist_name) VALUES ("AWOLNATION");
INSERT IGNORE INTO artists(artist_name) VALUES ("Rise Against");
INSERT IGNORE INTO artists(artist_name) VALUES ("NEEDTOBREATHE");
INSERT IGNORE INTO artists(artist_name) VALUES ("BANNERS");
INSERT IGNORE INTO artists(artist_name) VALUES ("Dirty Heads Featuring The Unlikely Candidates");
INSERT IGNORE INTO artists(artist_name) VALUES ("Imagine Dragons");
INSERT IGNORE INTO artists(artist_name) VALUES ("The Score");
INSERT IGNORE INTO artists(artist_name) VALUES ("Three Days Grace");
INSERT IGNORE INTO artists(artist_name) VALUES ("Nothing But Thieves");
INSERT IGNORE INTO artists(artist_name) VALUES ("St. Vincent");
INSERT IGNORE INTO artists(artist_name) VALUES ("The Neighbourhood");
INSERT IGNORE INTO artists(artist_name) VALUES ("Bebe Rexha & Florida Georgia Line");
INSERT IGNORE INTO artists(artist_name) VALUES ("Thomas Rhett");
INSERT IGNORE INTO artists(artist_name) VALUES ("Jason Aldean");
INSERT IGNORE INTO artists(artist_name) VALUES ("Kane Brown");
INSERT IGNORE INTO artists(artist_name) VALUES ("Chris Stapleton");
INSERT IGNORE INTO artists(artist_name) VALUES ("Luke Bryan");
INSERT IGNORE INTO artists(artist_name) VALUES ("Scotty McCreery");
INSERT IGNORE INTO artists(artist_name) VALUES ("Jordan Davis");
INSERT IGNORE INTO artists(artist_name) VALUES ("Devin Dawson");
INSERT IGNORE INTO artists(artist_name) VALUES ("Brett Eldredge");
INSERT IGNORE INTO artists(artist_name) VALUES ("Blake Shelton");
INSERT IGNORE INTO artists(artist_name) VALUES ("High Valley");
INSERT IGNORE INTO artists(artist_name) VALUES ("Luke Combs");
INSERT IGNORE INTO artists(artist_name) VALUES ("Dan + Shay");
INSERT IGNORE INTO artists(artist_name) VALUES ("Darius Rucker");
INSERT IGNORE INTO artists(artist_name) VALUES ("Morgan Wallen Featuring Florida Georgia Line");
INSERT IGNORE INTO artists(artist_name) VALUES ("Lee Brice");
INSERT IGNORE INTO artists(artist_name) VALUES ("Dierks Bentley");
INSERT IGNORE INTO artists(artist_name) VALUES ("Granger Smith");
INSERT IGNORE INTO artists(artist_name) VALUES ("Chris Lane Featuring Tori Kelly");
INSERT IGNORE INTO artists(artist_name) VALUES ("David Lee Murphy & Kenny Chesney");
INSERT IGNORE INTO artists(artist_name) VALUES ("Brantley Gilbert");
INSERT IGNORE INTO artists(artist_name) VALUES ("Brett Young");
INSERT IGNORE INTO artists(artist_name) VALUES ("Michael Ray");
INSERT IGNORE INTO artists(artist_name) VALUES ("Jake Owen");
INSERT IGNORE INTO artists(artist_name) VALUES ("Jon Pardi");
INSERT IGNORE INTO artists(artist_name) VALUES ("Cole Swindell");
INSERT IGNORE INTO artists(artist_name) VALUES ("Morgan Evans");
INSERT IGNORE INTO artists(artist_name) VALUES ("Dylan Scott");
INSERT IGNORE INTO artists(artist_name) VALUES ("Keith Urban");
INSERT IGNORE INTO artists(artist_name) VALUES ("Chris Janson");
INSERT IGNORE INTO artists(artist_name) VALUES ("Dustin Lynch");
INSERT IGNORE INTO artists(artist_name) VALUES ("Lady Antebellum");
INSERT IGNORE INTO artists(artist_name) VALUES ("Scotty McCreery");
INSERT IGNORE INTO artists(artist_name) VALUES ("Chris Young");
INSERT IGNORE INTO artists(artist_name) VALUES ("Lindsay Ell");
INSERT IGNORE INTO artists(artist_name) VALUES ("Ashley McBryde");
INSERT IGNORE INTO artists(artist_name) VALUES ("Justin Moore");
INSERT IGNORE INTO artists(artist_name) VALUES ("Lauren Alaina");
INSERT IGNORE INTO artists(artist_name) VALUES ("Chase Rice");
INSERT IGNORE INTO artists(artist_name) VALUES ("LANCO");
INSERT IGNORE INTO artists(artist_name) VALUES ("Keith Urban");
INSERT IGNORE INTO artists(artist_name) VALUES ("Carly Pearce");
INSERT IGNORE INTO artists(artist_name) VALUES ("Sir Rosevelt");
INSERT IGNORE INTO artists(artist_name) VALUES ("Kane Brown");
INSERT IGNORE INTO artists(artist_name) VALUES ("Brothers Osborne");
INSERT IGNORE INTO artists(artist_name) VALUES ("Chris Stapleton");
INSERT IGNORE INTO artists(artist_name) VALUES ("Runaway June");
INSERT IGNORE INTO artists(artist_name) VALUES ("Maren Morris");
INSERT IGNORE INTO artists(artist_name) VALUES ("Kacey Musgraves");
INSERT IGNORE INTO artists(artist_name) VALUES ("Imagine Dragons");
INSERT IGNORE INTO artists(artist_name) VALUES ("Portugal. The Man");
INSERT IGNORE INTO artists(artist_name) VALUES ("AJR Featuring Rivers Cuomo");
INSERT IGNORE INTO artists(artist_name) VALUES ("Foster The People");
INSERT IGNORE INTO artists(artist_name) VALUES ("The Killers");
INSERT IGNORE INTO artists(artist_name) VALUES ("lovelytheband");
INSERT IGNORE INTO artists(artist_name) VALUES ("WALK THE MOON");
INSERT IGNORE INTO artists(artist_name) VALUES ("Muse");
INSERT IGNORE INTO artists(artist_name) VALUES ("Alice Merton");
INSERT IGNORE INTO artists(artist_name) VALUES ("Moon Taxi");
INSERT IGNORE INTO artists(artist_name) VALUES ("Thirty Seconds To Mars");
INSERT IGNORE INTO artists(artist_name) VALUES ("Manchester Orchestra");
INSERT IGNORE INTO artists(artist_name) VALUES ("AWOLNATION");
INSERT IGNORE INTO artists(artist_name) VALUES ("Beck");
INSERT IGNORE INTO artists(artist_name) VALUES ("Sir Sly");
INSERT IGNORE INTO artists(artist_name) VALUES ("Vance Joy");
INSERT IGNORE INTO artists(artist_name) VALUES ("CHVRCHES");
INSERT IGNORE INTO artists(artist_name) VALUES ("Dirty Heads Featuring The Unlikely Candidates");
INSERT IGNORE INTO artists(artist_name) VALUES ("Rise Against");
INSERT IGNORE INTO artists(artist_name) VALUES ("Nathaniel Rateliff & The Night Sweats");
INSERT IGNORE INTO artists(artist_name) VALUES ("Joywave");
INSERT IGNORE INTO artists(artist_name) VALUES ("Robert DeLong + K.Flay");
INSERT IGNORE INTO artists(artist_name) VALUES ("Sofi Tukker Featuring NERVO, The Knocks & Alisa Ueno");
INSERT IGNORE INTO artists(artist_name) VALUES ("The Neighbourhood");
INSERT IGNORE INTO artists(artist_name) VALUES ("Two Feet");
INSERT IGNORE INTO artists(artist_name) VALUES ("St. Vincent");
INSERT IGNORE INTO artists(artist_name) VALUES ("Judah & The Lion");
INSERT IGNORE INTO artists(artist_name) VALUES ("Blue October");
INSERT IGNORE INTO artists(artist_name) VALUES ("Superorganism");
INSERT IGNORE INTO artists(artist_name) VALUES ("Nothing But Thieves");
INSERT IGNORE INTO artists(artist_name) VALUES ("Jack White");
INSERT IGNORE INTO artists(artist_name) VALUES ("Mansionair");
INSERT IGNORE INTO artists(artist_name) VALUES ("Dashboard Confessional");
INSERT IGNORE INTO artists(artist_name) VALUES ("Bishop Briggs");
INSERT IGNORE INTO artists(artist_name) VALUES ("Weezer");
INSERT IGNORE INTO artists(artist_name) VALUES ("Pearl Jam");
INSERT IGNORE INTO artists(artist_name) VALUES ("Jukebox The Ghost");
INSERT IGNORE INTO artists(artist_name) VALUES ("Jack White");
INSERT IGNORE INTO artists(artist_name) VALUES ("SYML");
INSERT IGNORE INTO artists(artist_name) VALUES ("Yungblud");
INSERT IGNORE INTO artists(artist_name) VALUES ("Drake");
INSERT IGNORE INTO artists(artist_name) VALUES ("Bruno Mars & Cardi B");
INSERT IGNORE INTO artists(artist_name) VALUES ("Post Malone Featuring Ty Dolla $ign");
INSERT IGNORE INTO artists(artist_name) VALUES ("The Weeknd & Kendrick Lamar");
INSERT IGNORE INTO artists(artist_name) VALUES ("BlocBoy JB Featuring Drake");
INSERT IGNORE INTO artists(artist_name) VALUES ("Kendrick Lamar & SZA");
INSERT IGNORE INTO artists(artist_name) VALUES ("Migos");
INSERT IGNORE INTO artists(artist_name) VALUES ("Post Malone Featuring 21 Savage");
INSERT IGNORE INTO artists(artist_name) VALUES ("NF");
INSERT IGNORE INTO artists(artist_name) VALUES ("Offset & Metro Boomin");
INSERT IGNORE INTO artists(artist_name) VALUES ("G-Eazy & Halsey");
INSERT IGNORE INTO artists(artist_name) VALUES ("XXXTentacion");
INSERT IGNORE INTO artists(artist_name) VALUES ("Jay Rock, Kendrick Lamar, Future & James Blake");
INSERT IGNORE INTO artists(artist_name) VALUES ("Post Malone");
INSERT IGNORE INTO artists(artist_name) VALUES ("Rich The Kid");
INSERT IGNORE INTO artists(artist_name) VALUES ("Logic & Marshmello");
INSERT IGNORE INTO artists(artist_name) VALUES ("Cardi B Featuring 21 Savage");
INSERT IGNORE INTO artists(artist_name) VALUES ("YoungBoy Never Broke Again");
INSERT IGNORE INTO artists(artist_name) VALUES ("Migos, Nicki Minaj & Cardi B");
INSERT IGNORE INTO artists(artist_name) VALUES ("Rich The Kid Featuring Kendrick Lamar");
INSERT IGNORE INTO artists(artist_name) VALUES ("Logic");
INSERT IGNORE INTO artists(artist_name) VALUES ("A$AP Ferg Featuring Nicki Minaj");
INSERT IGNORE INTO artists(artist_name) VALUES ("DJ Khaled Featuring JAY Z, Future & B");
INSERT IGNORE INTO artists(artist_name) VALUES ("6ix9ine");
INSERT IGNORE INTO artists(artist_name) VALUES ("6ix9ine");
INSERT IGNORE INTO artists(artist_name) VALUES ("Logic Featuring Wiz Khalifa");
INSERT IGNORE INTO artists(artist_name) VALUES ("XXXTentacion");
INSERT IGNORE INTO artists(artist_name) VALUES ("Logic");
INSERT IGNORE INTO artists(artist_name) VALUES ("N*E*R*D & Rihanna");
INSERT IGNORE INTO artists(artist_name) VALUES ("Lil Skies Featuring Landon Cube");
INSERT IGNORE INTO artists(artist_name) VALUES ("Lil Yachty Featuring NBA YoungBoy");
INSERT IGNORE INTO artists(artist_name) VALUES ("Logic");
INSERT IGNORE INTO artists(artist_name) VALUES ("Migos Featuring Drake");
INSERT IGNORE INTO artists(artist_name) VALUES ("Famous Dex Featuring A$AP Rocky");
INSERT IGNORE INTO artists(artist_name) VALUES ("Derez De'Shon");
INSERT IGNORE INTO artists(artist_name) VALUES ("Lil Yachty Featuring Trippie Redd");
INSERT IGNORE INTO artists(artist_name) VALUES ("Logic");
INSERT IGNORE INTO artists(artist_name) VALUES ("Rae Sremmurd & Juicy J");
INSERT IGNORE INTO artists(artist_name) VALUES ("Lil Skies Featuring Landon Cube");
INSERT IGNORE INTO artists(artist_name) VALUES ("Logic Featuring Big Sean");
INSERT IGNORE INTO artists(artist_name) VALUES ("Eminem Featuring Ed Sheeran");
INSERT IGNORE INTO artists(artist_name) VALUES ("Logic");
INSERT IGNORE INTO artists(artist_name) VALUES ("Lil Yachty Featuring Ugly God");
INSERT IGNORE INTO artists(artist_name) VALUES ("Blac Youngsta");
INSERT IGNORE INTO artists(artist_name) VALUES ("Migos");
INSERT IGNORE INTO artists(artist_name) VALUES ("ScHoolboy Q, 2 Chainz & Saudi");
INSERT IGNORE INTO artists(artist_name) VALUES ("Jacquees X Dej Loaf");
INSERT IGNORE INTO artists(artist_name) VALUES ("Logic");
INSERT IGNORE INTO artists(artist_name) VALUES ("Logic Featuring Young Sinatra");
INSERT IGNORE INTO artists(artist_name) VALUES ("Trippie Redd Featuring Travis Scott");
