INSERT IGNORE INTO songs(song_name, genre, artist) VALUES ("Him & I","Pop","G-Eazy & Halsey");
INSERT IGNORE INTO songs(song_name, genre, artist) VALUES ("Let You Down","Pop","NF");
INSERT IGNORE INTO songs(song_name, genre, artist) VALUES ("Finesse","Pop","Bruno Mars & Cardi B");
INSERT IGNORE INTO songs(song_name, genre, artist) VALUES ("Perfect","Pop","Ed Sheeran");
INSERT IGNORE INTO songs(song_name, genre, artist) VALUES ("The Middle","Pop","Zedd, Maren Morris & Grey");
INSERT IGNORE INTO songs(song_name, genre, artist) VALUES ("Meant To Be","Pop","Bebe Rexha & Florida Georgia Line");
INSERT IGNORE INTO songs(song_name, genre, artist) VALUES ("New Rules","Pop","Dua Lipa");
INSERT IGNORE INTO songs(song_name, genre, artist) VALUES ("Lights Down Low","Pop","MAX Featuring gnash");
INSERT IGNORE INTO songs(song_name, genre, artist) VALUES ("Never Be The Same","Pop","Camila Cabello");
INSERT IGNORE INTO songs(song_name, genre, artist) VALUES ("Wolves","Pop","Selena Gomez X Marshmello");
INSERT IGNORE INTO songs(song_name, genre, artist) VALUES ("Pray For Me","Pop","The Weeknd & Kendrick Lamar");
INSERT IGNORE INTO songs(song_name, genre, artist) VALUES ("God's Plan","Pop","Drake");
INSERT IGNORE INTO songs(song_name, genre, artist) VALUES ("Havana","Pop","Camila Cabello Featuring Young Thug");
INSERT IGNORE INTO songs(song_name, genre, artist) VALUES ("Bad At Love","Pop","Halsey");
INSERT IGNORE INTO songs(song_name, genre, artist) VALUES ("Whatever It Takes","Pop","Imagine Dragons");
INSERT IGNORE INTO songs(song_name, genre, artist) VALUES ("Wait","Pop","Maroon 5");
INSERT IGNORE INTO songs(song_name, genre, artist) VALUES ("Say Something","Pop","Justin Timberlake Featuring Chris Stapleton");
INSERT IGNORE INTO songs(song_name, genre, artist) VALUES ("I Like Me Better","Pop","Lauv");
INSERT IGNORE INTO songs(song_name, genre, artist) VALUES ("Friends","Pop","Marshmello & Anne-Marie");
INSERT IGNORE INTO songs(song_name, genre, artist) VALUES ("Tell Me You Love Me","Pop","Demi Lovato");
INSERT IGNORE INTO songs(song_name, genre, artist) VALUES ("No Excuses","Pop","Meghan Trainor");
INSERT IGNORE INTO songs(song_name, genre, artist) VALUES ("Lemon","Pop","N*E*R*D & Rihanna");
INSERT IGNORE INTO songs(song_name, genre, artist) VALUES ("All The Stars","Pop","Kendrick Lamar & SZA");
INSERT IGNORE INTO songs(song_name, genre, artist) VALUES ("Mine","Pop","Bazzi");
INSERT IGNORE INTO songs(song_name, genre, artist) VALUES ("Want You Back","Pop","5 Seconds Of Summer");
INSERT IGNORE INTO songs(song_name, genre, artist) VALUES ("IDGAF","Pop","Dua Lipa");
INSERT IGNORE INTO songs(song_name, genre, artist) VALUES ("My My My!","Pop","Troye Sivan");
INSERT IGNORE INTO songs(song_name, genre, artist) VALUES ("On The Loose","Pop","Niall Horan");
INSERT IGNORE INTO songs(song_name, genre, artist) VALUES ("Psycho","Pop","Post Malone Featuring Ty Dolla $ign");
INSERT IGNORE INTO songs(song_name, genre, artist) VALUES ("Beg","Pop","Jack & Jack");
INSERT IGNORE INTO songs(song_name, genre, artist) VALUES ("Beautiful Trauma","Pop","P!nk");
INSERT IGNORE INTO songs(song_name, genre, artist) VALUES ("Delicate","Pop","Taylor Swift");
INSERT IGNORE INTO songs(song_name, genre, artist) VALUES ("Walk On Water","Pop","Thirty Seconds To Mars");
INSERT IGNORE INTO songs(song_name, genre, artist) VALUES ("Trust Fund Baby","Pop","Why Don't We");
INSERT IGNORE INTO songs(song_name, genre, artist) VALUES ("No Roots","Pop","Alice Merton");
INSERT IGNORE INTO songs(song_name, genre, artist) VALUES ("Sit Next To Me","Pop","Foster The People");
INSERT IGNORE INTO songs(song_name, genre, artist) VALUES ("Love.","Pop","Kendrick Lamar Featuring Zacari");
INSERT IGNORE INTO songs(song_name, genre, artist) VALUES ("Merengue","Pop","Kent Jones");
INSERT IGNORE INTO songs(song_name, genre, artist) VALUES ("Everyday","Pop","Logic & Marshmello");
INSERT IGNORE INTO songs(song_name, genre, artist) VALUES ("Curious","Pop","Hayley Kiyoko");
INSERT IGNORE INTO songs(song_name, genre, artist) VALUES ("Thunder","Rock","Imagine Dragons");
INSERT IGNORE INTO songs(song_name, genre, artist) VALUES ("Whatever It Takes","Rock","Imagine Dragons");
INSERT IGNORE INTO songs(song_name, genre, artist) VALUES ("Feel It Still","Rock","Portugal. The Man");
INSERT IGNORE INTO songs(song_name, genre, artist) VALUES ("Believer","Rock","Imagine Dragons");
INSERT IGNORE INTO songs(song_name, genre, artist) VALUES ("Zombie","Rock","Bad Wolves");
INSERT IGNORE INTO songs(song_name, genre, artist) VALUES ("Sit Next To Me","Rock","Foster The People");
INSERT IGNORE INTO songs(song_name, genre, artist) VALUES ("No Roots","Rock","Alice Merton");
INSERT IGNORE INTO songs(song_name, genre, artist) VALUES ("One Foot","Rock","WALK THE MOON");
INSERT IGNORE INTO songs(song_name, genre, artist) VALUES ("Devil","Rock","Shinedown");
INSERT IGNORE INTO songs(song_name, genre, artist) VALUES ("Next To Me","Rock","Imagine Dragons");
INSERT IGNORE INTO songs(song_name, genre, artist) VALUES ("Gone Away","Rock","Five Finger Death Punch");
INSERT IGNORE INTO songs(song_name, genre, artist) VALUES ("Live In The Moment","Rock","Portugal. The Man");
INSERT IGNORE INTO songs(song_name, genre, artist) VALUES ("Broken","Rock","lovelytheband");
INSERT IGNORE INTO songs(song_name, genre, artist) VALUES ("The Mountain","Rock","Three Days Grace");
INSERT IGNORE INTO songs(song_name, genre, artist) VALUES ("Wild Love","Rock","James Bay");
INSERT IGNORE INTO songs(song_name, genre, artist) VALUES ("Hurricane","Rock","The Band Of Heathens");
INSERT IGNORE INTO songs(song_name, genre, artist) VALUES ("Pink Lemonade","Rock","James Bay");
INSERT IGNORE INTO songs(song_name, genre, artist) VALUES ("Thought Contagion","Rock","Muse");
INSERT IGNORE INTO songs(song_name, genre, artist) VALUES ("You Worry Me","Rock","Nathaniel Rateliff & The Night Sweats");
INSERT IGNORE INTO songs(song_name, genre, artist) VALUES ("Red Cold River","Rock","Breaking Benjamin");
INSERT IGNORE INTO songs(song_name, genre, artist) VALUES ("Run For Cover","Rock","The Killers");
INSERT IGNORE INTO songs(song_name, genre, artist) VALUES ("Bulletproof","Rock","Godsmack");
INSERT IGNORE INTO songs(song_name, genre, artist) VALUES ("I Feel Like I'm Drowning","Rock","Two Feet");
INSERT IGNORE INTO songs(song_name, genre, artist) VALUES ("Saturday Sun","Rock","Vance Joy");
INSERT IGNORE INTO songs(song_name, genre, artist) VALUES ("Safari Song","Rock","Greta Van Fleet");
INSERT IGNORE INTO songs(song_name, genre, artist) VALUES ("Mystery Of Love","Rock","Sufjan Stevens");
INSERT IGNORE INTO songs(song_name, genre, artist) VALUES ("Waking Lions","Rock","Pop Evil");
INSERT IGNORE INTO songs(song_name, genre, artist) VALUES ("Hold Me Tight Or Don't","Rock","Fall Out Boy");
INSERT IGNORE INTO songs(song_name, genre, artist) VALUES ("Born For Greatness","Rock","Papa Roach");
INSERT IGNORE INTO songs(song_name, genre, artist) VALUES ("Scary Love","Rock","The Neighbourhood");
INSERT IGNORE INTO songs(song_name, genre, artist) VALUES ("Dangerous Night","Rock","Thirty Seconds To Mars");
INSERT IGNORE INTO songs(song_name, genre, artist) VALUES ("Can't Deny Me","Rock","Pearl Jam");
INSERT IGNORE INTO songs(song_name, genre, artist) VALUES ("The Gold","Rock","Manchester Orchestra");
INSERT IGNORE INTO songs(song_name, genre, artist) VALUES ("Thunder/Young Dumb & Broke (Medley)","Rock","Imagine Dragons + Khalid");
INSERT IGNORE INTO songs(song_name, genre, artist) VALUES ("&Run","Rock","Sir Sly");
INSERT IGNORE INTO songs(song_name, genre, artist) VALUES ("Where's My Love","Rock","SYML");
INSERT IGNORE INTO songs(song_name, genre, artist) VALUES ("Get Out","Rock","CHVRCHES");
INSERT IGNORE INTO songs(song_name, genre, artist) VALUES ("Nervous","Rock","The Neighbourhood");
INSERT IGNORE INTO songs(song_name, genre, artist) VALUES ("Hurt Somebody","Rock","Noah Kahan & Julia Michaels");
INSERT IGNORE INTO songs(song_name, genre, artist) VALUES ("Handyman","Rock","AWOLNATION");
INSERT IGNORE INTO songs(song_name, genre, artist) VALUES ("House On Fire","Rock","Rise Against");
INSERT IGNORE INTO songs(song_name, genre, artist) VALUES ("Walking On Water","Rock","NEEDTOBREATHE");
INSERT IGNORE INTO songs(song_name, genre, artist) VALUES ("Someone To You","Rock","BANNERS");
INSERT IGNORE INTO songs(song_name, genre, artist) VALUES ("Celebrate","Rock","Dirty Heads Featuring The Unlikely Candidates");
INSERT IGNORE INTO songs(song_name, genre, artist) VALUES ("Rise Up","Rock","Imagine Dragons");
INSERT IGNORE INTO songs(song_name, genre, artist) VALUES ("Legend","Rock","The Score");
INSERT IGNORE INTO songs(song_name, genre, artist) VALUES ("Right Left Wrong","Rock","Three Days Grace");
INSERT IGNORE INTO songs(song_name, genre, artist) VALUES ("Sorry","Rock","Nothing But Thieves");
INSERT IGNORE INTO songs(song_name, genre, artist) VALUES ("Los Ageless","Rock","St. Vincent");
INSERT IGNORE INTO songs(song_name, genre, artist) VALUES ("Void","Rock","The Neighbourhood");
INSERT IGNORE INTO songs(song_name, genre, artist) VALUES ("Meant To Be","Country","Bebe Rexha & Florida Georgia Line");
INSERT IGNORE INTO songs(song_name, genre, artist) VALUES ("Marry Me","Country","Thomas Rhett");
INSERT IGNORE INTO songs(song_name, genre, artist) VALUES ("You Make It Easy","Country","Jason Aldean");
INSERT IGNORE INTO songs(song_name, genre, artist) VALUES ("Heaven","Country","Kane Brown");
INSERT IGNORE INTO songs(song_name, genre, artist) VALUES ("Broken Halos","Country","Chris Stapleton");
INSERT IGNORE INTO songs(song_name, genre, artist) VALUES ("Most People Are Good","Country","Luke Bryan");
INSERT IGNORE INTO songs(song_name, genre, artist) VALUES ("Five More Minutes","Country","Scotty McCreery");
INSERT IGNORE INTO songs(song_name, genre, artist) VALUES ("Singles You Up","Country","Jordan Davis");
INSERT IGNORE INTO songs(song_name, genre, artist) VALUES ("All On Me","Country","Devin Dawson");
INSERT IGNORE INTO songs(song_name, genre, artist) VALUES ("The Long Way","Country","Brett Eldredge");
INSERT IGNORE INTO songs(song_name, genre, artist) VALUES ("I Lived It","Country","Blake Shelton");
INSERT IGNORE INTO songs(song_name, genre, artist) VALUES ("She's With Me","Country","High Valley");
INSERT IGNORE INTO songs(song_name, genre, artist) VALUES ("One Number Away","Country","Luke Combs");
INSERT IGNORE INTO songs(song_name, genre, artist) VALUES ("Tequila","Country","Dan + Shay");
INSERT IGNORE INTO songs(song_name, genre, artist) VALUES ("For The First Time","Country","Darius Rucker");
INSERT IGNORE INTO songs(song_name, genre, artist) VALUES ("Up Down","Country","Morgan Wallen Featuring Florida Georgia Line");
INSERT IGNORE INTO songs(song_name, genre, artist) VALUES ("Boy","Country","Lee Brice");
INSERT IGNORE INTO songs(song_name, genre, artist) VALUES ("Woman, Amen","Country","Dierks Bentley");
INSERT IGNORE INTO songs(song_name, genre, artist) VALUES ("Happens Like That","Country","Granger Smith");
INSERT IGNORE INTO songs(song_name, genre, artist) VALUES ("Take Back Home Girl","Country","Chris Lane Featuring Tori Kelly");
INSERT IGNORE INTO songs(song_name, genre, artist) VALUES ("Everything's Gonna Be Alright","Country","David Lee Murphy & Kenny Chesney");
INSERT IGNORE INTO songs(song_name, genre, artist) VALUES ("Ones That Like Me","Country","Brantley Gilbert");
INSERT IGNORE INTO songs(song_name, genre, artist) VALUES ("Mercy","Country","Brett Young");
INSERT IGNORE INTO songs(song_name, genre, artist) VALUES ("Get To You","Country","Michael Ray");
INSERT IGNORE INTO songs(song_name, genre, artist) VALUES ("I Was Jack (You Were Diane)","Country","Jake Owen");
INSERT IGNORE INTO songs(song_name, genre, artist) VALUES ("She Ain't In It","Country","Jon Pardi");
INSERT IGNORE INTO songs(song_name, genre, artist) VALUES ("Break Up In The End","Country","Cole Swindell");
INSERT IGNORE INTO songs(song_name, genre, artist) VALUES ("Kiss Somebody","Country","Morgan Evans");
INSERT IGNORE INTO songs(song_name, genre, artist) VALUES ("Hooked","Country","Dylan Scott");
INSERT IGNORE INTO songs(song_name, genre, artist) VALUES ("Female","Country","Keith Urban");
INSERT IGNORE INTO songs(song_name, genre, artist) VALUES ("Drunk Girl","Country","Chris Janson");
INSERT IGNORE INTO songs(song_name, genre, artist) VALUES ("I'd Be Jealous Too","Country","Dustin Lynch");
INSERT IGNORE INTO songs(song_name, genre, artist) VALUES ("Heart Break","Country","Lady Antebellum");
INSERT IGNORE INTO songs(song_name, genre, artist) VALUES ("This Is It","Country","Scotty McCreery");
INSERT IGNORE INTO songs(song_name, genre, artist) VALUES ("Hangin' On","Country","Chris Young");
INSERT IGNORE INTO songs(song_name, genre, artist) VALUES ("Criminal","Country","Lindsay Ell");
INSERT IGNORE INTO songs(song_name, genre, artist) VALUES ("A Little Dive Bar In Dahlonega","Country","Ashley McBryde");
INSERT IGNORE INTO songs(song_name, genre, artist) VALUES ("Kinda Don't Care","Country","Justin Moore");
INSERT IGNORE INTO songs(song_name, genre, artist) VALUES ("Doin' Fine","Country","Lauren Alaina");
INSERT IGNORE INTO songs(song_name, genre, artist) VALUES ("Three Chords & The Truth","Country","Chase Rice");
INSERT IGNORE INTO songs(song_name, genre, artist) VALUES ("Born To Love You","Country","LANCO");
INSERT IGNORE INTO songs(song_name, genre, artist) VALUES ("Parallel Line","Country","Keith Urban");
INSERT IGNORE INTO songs(song_name, genre, artist) VALUES ("Hide The Wine","Country","Carly Pearce");
INSERT IGNORE INTO songs(song_name, genre, artist) VALUES ("Something 'Bout You","Country","Sir Rosevelt");
INSERT IGNORE INTO songs(song_name, genre, artist) VALUES ("What's Mine Is Yours","Country","Kane Brown");
INSERT IGNORE INTO songs(song_name, genre, artist) VALUES ("Shoot Me Straight","Country","Brothers Osborne");
INSERT IGNORE INTO songs(song_name, genre, artist) VALUES ("Millionaire","Country","Chris Stapleton");
INSERT IGNORE INTO songs(song_name, genre, artist) VALUES ("Wild West","Country","Runaway June");
INSERT IGNORE INTO songs(song_name, genre, artist) VALUES ("Rich","Country","Maren Morris");
INSERT IGNORE INTO songs(song_name, genre, artist) VALUES ("Butterflies","Country","Kacey Musgraves");
INSERT IGNORE INTO songs(song_name, genre, artist) VALUES ("Whatever It Takes","Alternative","Imagine Dragons");
INSERT IGNORE INTO songs(song_name, genre, artist) VALUES ("Live In The Moment","Alternative","Portugal. The Man");
INSERT IGNORE INTO songs(song_name, genre, artist) VALUES ("Sober Up","Alternative","AJR Featuring Rivers Cuomo");
INSERT IGNORE INTO songs(song_name, genre, artist) VALUES ("Sit Next To Me","Alternative","Foster The People");
INSERT IGNORE INTO songs(song_name, genre, artist) VALUES ("Run For Cover","Alternative","The Killers");
INSERT IGNORE INTO songs(song_name, genre, artist) VALUES ("Broken","Alternative","lovelytheband");
INSERT IGNORE INTO songs(song_name, genre, artist) VALUES ("One Foot","Alternative","WALK THE MOON");
INSERT IGNORE INTO songs(song_name, genre, artist) VALUES ("Thought Contagion","Alternative","Muse");
INSERT IGNORE INTO songs(song_name, genre, artist) VALUES ("No Roots","Alternative","Alice Merton");
INSERT IGNORE INTO songs(song_name, genre, artist) VALUES ("Two High","Alternative","Moon Taxi");
INSERT IGNORE INTO songs(song_name, genre, artist) VALUES ("Dangerous Night","Alternative","Thirty Seconds To Mars");
INSERT IGNORE INTO songs(song_name, genre, artist) VALUES ("The Gold","Alternative","Manchester Orchestra");
INSERT IGNORE INTO songs(song_name, genre, artist) VALUES ("Handyman","Alternative","AWOLNATION");
INSERT IGNORE INTO songs(song_name, genre, artist) VALUES ("Up All Night","Alternative","Beck");
INSERT IGNORE INTO songs(song_name, genre, artist) VALUES ("&Run","Alternative","Sir Sly");
INSERT IGNORE INTO songs(song_name, genre, artist) VALUES ("Saturday Sun","Alternative","Vance Joy");
INSERT IGNORE INTO songs(song_name, genre, artist) VALUES ("Get Out","Alternative","CHVRCHES");
INSERT IGNORE INTO songs(song_name, genre, artist) VALUES ("Celebrate","Alternative","Dirty Heads Featuring The Unlikely Candidates");
INSERT IGNORE INTO songs(song_name, genre, artist) VALUES ("House On Fire","Alternative","Rise Against");
INSERT IGNORE INTO songs(song_name, genre, artist) VALUES ("You Worry Me","Alternative","Nathaniel Rateliff & The Night Sweats");
INSERT IGNORE INTO songs(song_name, genre, artist) VALUES ("Doubt","Alternative","Joywave");
INSERT IGNORE INTO songs(song_name, genre, artist) VALUES ("Favorite Color Is Blue","Alternative","Robert DeLong + K.Flay");
INSERT IGNORE INTO songs(song_name, genre, artist) VALUES ("Best Friend","Alternative","Sofi Tukker Featuring NERVO, The Knocks & Alisa Ueno");
INSERT IGNORE INTO songs(song_name, genre, artist) VALUES ("Scary Love","Alternative","The Neighbourhood");
INSERT IGNORE INTO songs(song_name, genre, artist) VALUES ("I Feel Like I'm Drowning","Alternative","Two Feet");
INSERT IGNORE INTO songs(song_name, genre, artist) VALUES ("Los Ageless","Alternative","St. Vincent");
INSERT IGNORE INTO songs(song_name, genre, artist) VALUES ("Going To Mars","Alternative","Judah & The Lion");
INSERT IGNORE INTO songs(song_name, genre, artist) VALUES ("I Hope You're Happy","Alternative","Blue October");
INSERT IGNORE INTO songs(song_name, genre, artist) VALUES ("Everybody Wants To Be Famous","Alternative","Superorganism");
INSERT IGNORE INTO songs(song_name, genre, artist) VALUES ("Sorry","Alternative","Nothing But Thieves");
INSERT IGNORE INTO songs(song_name, genre, artist) VALUES ("Over And Over And Over","Alternative","Jack White");
INSERT IGNORE INTO songs(song_name, genre, artist) VALUES ("Astronaut (Something About Your Love)","Alternative","Mansionair");
INSERT IGNORE INTO songs(song_name, genre, artist) VALUES ("We Fight","Alternative","Dashboard Confessional");
INSERT IGNORE INTO songs(song_name, genre, artist) VALUES ("White Flag","Alternative","Bishop Briggs");
INSERT IGNORE INTO songs(song_name, genre, artist) VALUES ("Happy Hour","Alternative","Weezer");
INSERT IGNORE INTO songs(song_name, genre, artist) VALUES ("Can't Deny Me","Alternative","Pearl Jam");
INSERT IGNORE INTO songs(song_name, genre, artist) VALUES ("Everybody's Lonely","Alternative","Jukebox The Ghost");
INSERT IGNORE INTO songs(song_name, genre, artist) VALUES ("Connected By Love","Alternative","Jack White");
INSERT IGNORE INTO songs(song_name, genre, artist) VALUES ("Where's My Love","Alternative","SYML");
INSERT IGNORE INTO songs(song_name, genre, artist) VALUES ("I Love You, Will You Marry Me","Alternative","Yungblud");
INSERT IGNORE INTO songs(song_name, genre, artist) VALUES ("God's Plan","Hip Hop","Drake");
INSERT IGNORE INTO songs(song_name, genre, artist) VALUES ("Finesse","Hip Hop","Bruno Mars & Cardi B");
INSERT IGNORE INTO songs(song_name, genre, artist) VALUES ("Psycho","Hip Hop","Post Malone Featuring Ty Dolla $ign");
INSERT IGNORE INTO songs(song_name, genre, artist) VALUES ("Pray For Me","Hip Hop","The Weeknd & Kendrick Lamar");
INSERT IGNORE INTO songs(song_name, genre, artist) VALUES ("Look Alive","Hip Hop","BlocBoy JB Featuring Drake");
INSERT IGNORE INTO songs(song_name, genre, artist) VALUES ("All The Stars","Hip Hop","Kendrick Lamar & SZA");
INSERT IGNORE INTO songs(song_name, genre, artist) VALUES ("Stir Fry","Hip Hop","Migos");
INSERT IGNORE INTO songs(song_name, genre, artist) VALUES ("Rockstar","Hip Hop","Post Malone Featuring 21 Savage");
INSERT IGNORE INTO songs(song_name, genre, artist) VALUES ("Let You Down","Hip Hop","NF");
INSERT IGNORE INTO songs(song_name, genre, artist) VALUES ("Ric Flair Drip","Hip Hop","Offset & Metro Boomin");
INSERT IGNORE INTO songs(song_name, genre, artist) VALUES ("Him & I","Hip Hop","G-Eazy & Halsey");
INSERT IGNORE INTO songs(song_name, genre, artist) VALUES ("Sad!","Hip Hop","XXXTentacion");
INSERT IGNORE INTO songs(song_name, genre, artist) VALUES ("King's Dead","Hip Hop","Jay Rock, Kendrick Lamar, Future & James Blake");
INSERT IGNORE INTO songs(song_name, genre, artist) VALUES ("I Fall Apart","Hip Hop","Post Malone");
INSERT IGNORE INTO songs(song_name, genre, artist) VALUES ("Plug Walk","Hip Hop","Rich The Kid");
INSERT IGNORE INTO songs(song_name, genre, artist) VALUES ("Everyday","Hip Hop","Logic & Marshmello");
INSERT IGNORE INTO songs(song_name, genre, artist) VALUES ("Bartier Cardi","Hip Hop","Cardi B Featuring 21 Savage");
INSERT IGNORE INTO songs(song_name, genre, artist) VALUES ("Outside Today","Hip Hop","YoungBoy Never Broke Again");
INSERT IGNORE INTO songs(song_name, genre, artist) VALUES ("MotorSport","Hip Hop","Migos, Nicki Minaj & Cardi B");
INSERT IGNORE INTO songs(song_name, genre, artist) VALUES ("New Freezer","Hip Hop","Rich The Kid Featuring Kendrick Lamar");
INSERT IGNORE INTO songs(song_name, genre, artist) VALUES ("44 More","Hip Hop","Logic");
INSERT IGNORE INTO songs(song_name, genre, artist) VALUES ("Plain Jane","Hip Hop","A$AP Ferg Featuring Nicki Minaj");
INSERT IGNORE INTO songs(song_name, genre, artist) VALUES ("Top Off","Hip Hop","DJ Khaled Featuring JAY Z, Future & B");
INSERT IGNORE INTO songs(song_name, genre, artist) VALUES ("Billy","Hip Hop","6ix9ine");
INSERT IGNORE INTO songs(song_name, genre, artist) VALUES ("Gummo","Hip Hop","6ix9ine");
INSERT IGNORE INTO songs(song_name, genre, artist) VALUES ("Indica Badu","Hip Hop","Logic Featuring Wiz Khalifa");
INSERT IGNORE INTO songs(song_name, genre, artist) VALUES ("Changes","Hip Hop","XXXTentacion");
INSERT IGNORE INTO songs(song_name, genre, artist) VALUES ("Contra","Hip Hop","Logic");
INSERT IGNORE INTO songs(song_name, genre, artist) VALUES ("Lemon","Hip Hop","N*E*R*D & Rihanna");
INSERT IGNORE INTO songs(song_name, genre, artist) VALUES ("Nowadays","Hip Hop","Lil Skies Featuring Landon Cube");
INSERT IGNORE INTO songs(song_name, genre, artist) VALUES ("NBAYoungboat","Hip Hop","Lil Yachty Featuring NBA YoungBoy");
INSERT IGNORE INTO songs(song_name, genre, artist) VALUES ("Overnight","Hip Hop","Logic");
INSERT IGNORE INTO songs(song_name, genre, artist) VALUES ("Walk It Talk It","Hip Hop","Migos Featuring Drake");
INSERT IGNORE INTO songs(song_name, genre, artist) VALUES ("Pick It Up","Hip Hop","Famous Dex Featuring A$AP Rocky");
INSERT IGNORE INTO songs(song_name, genre, artist) VALUES ("Hardaway","Hip Hop","Derez De'Shon");
INSERT IGNORE INTO songs(song_name, genre, artist) VALUES ("66","Hip Hop","Lil Yachty Featuring Trippie Redd");
INSERT IGNORE INTO songs(song_name, genre, artist) VALUES ("Midnight","Hip Hop","Logic");
INSERT IGNORE INTO songs(song_name, genre, artist) VALUES ("Powerglide","Hip Hop","Rae Sremmurd & Juicy J");
INSERT IGNORE INTO songs(song_name, genre, artist) VALUES ("Red Roses","Hip Hop","Lil Skies Featuring Landon Cube");
INSERT IGNORE INTO songs(song_name, genre, artist) VALUES ("Wassup","Hip Hop","Logic Featuring Big Sean");
INSERT IGNORE INTO songs(song_name, genre, artist) VALUES ("River","Hip Hop","Eminem Featuring Ed Sheeran");
INSERT IGNORE INTO songs(song_name, genre, artist) VALUES ("Yuck","Hip Hop","Logic");
INSERT IGNORE INTO songs(song_name, genre, artist) VALUES ("Boom!","Hip Hop","Lil Yachty Featuring Ugly God");
INSERT IGNORE INTO songs(song_name, genre, artist) VALUES ("Booty","Hip Hop","Blac Youngsta");
INSERT IGNORE INTO songs(song_name, genre, artist) VALUES ("Narcos","Hip Hop","Migos");
INSERT IGNORE INTO songs(song_name, genre, artist) VALUES ("X","Hip Hop","ScHoolboy Q, 2 Chainz & Saudi");
INSERT IGNORE INTO songs(song_name, genre, artist) VALUES ("At The Club","Hip Hop","Jacquees X Dej Loaf");
INSERT IGNORE INTO songs(song_name, genre, artist) VALUES ("BoomTrap Protocol","Hip Hop","Logic");
INSERT IGNORE INTO songs(song_name, genre, artist) VALUES ("Warm It Up","Hip Hop","Logic Featuring Young Sinatra");
INSERT IGNORE INTO songs(song_name, genre, artist) VALUES ("Dark Knight Dummo","Hip Hop","Trippie Redd Featuring Travis Scott");
